services:
  mysql-docker-container:
    image: mysql:5.7
    volumes:
      - /data/mysql
      - ./sql_scripts:/docker-entrypoint-initdb.d/:ro
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - quiz-mysql-network
      
  quizApp:
    image: quiz-image:latest
    build:
      dockerfile: Dockerfile
      context: ""
    depends_on:
      - mysql-docker-container
    ports:
      - 8081:8081
    environment:
      - MYSQL_HOST=mysql-docker-container
      - MYSQL_DATABASE=quiz_app
      - MYSQL_PORT=3306
    volumes:
      - /data/spring-boot-app
    tty: true
    networks:
      - quiz-mysql-network
      
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
        
networks:
    quiz-mysql-network:
      driver: bridge